### ISSUE TITLE
Is this a SkillTree issue?

### ISSUE THREAD

**Issue by Beanius** [Z-Doctor/SkillTree#9]
Died in my game then the game crashed, tried to log back in and my console spammed:

[15:24:43] [Server thread/WARN] [FML]: * Receiver EntityPlayerMP['Beanius'/26542, l='Biome Bundle', x=-295.36, y=151.95, z=-308.64] is Dead!
[15:24:43] [Server thread/WARN] [FML]: *  at zdoctor.skilltree.api.SkillTreeApi.syncSkills(SkillTreeApi.java:178)
[15:24:43] [Server thread/WARN] [FML]: *  at zdoctor.skilltree.skills.CapabilitySkillHandler.playerTracking(CapabilitySkillHandler.java:114)
[15:24:43] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1577_CapabilitySkillHandler_playerTracking_StartTracking.invoke(.dynamic)
[15:24:43] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[15:24:43] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[15:24:43] [Server thread/WARN] [FML]: *  at net.minecraftforge.event.ForgeEventFactory.onStartEntityTracking(ForgeEventFactory.java:367)...
[15:24:43] [Server thread/WARN] [FML]: ****************************************

while nothing else happened

**Comment by XZcutable** [comment]
Hmm. Not sure. Can you send the full log? Did anything bad happen like lost skills?

**Comment by XZcutable** [comment]
I'm just going to go ahead and add some checks to make sure that targets aren't dead along with add some null checks in my code. I'll leave this open until I can take a look at the whole log.

**Comment by Beanius** [comment]
I'ma try again with the new version of SkillTree B)

**Comment by Beanius** [comment]
https://gist.github.com/Beanius/f665dcc7c23efc00e5ed72f061fc31cc

Still crashes

**Comment by XZcutable** [comment]
Yeah, I made some quick changes, but then I realized that I was working on an update that was incompatible. I had to pull the update and finish my changes first. Waiting on a few things before doing that.

**Comment by Beanius** [comment]
oki doki B)
